#ifndef _UNTECH_GUI_WIDGETS_DEFAULTS_H_
#define _UNTECH_GUI_WIDGETS_DEFAULTS_H_

const unsigned DEFAULT_ROW_SPACING = 3;
const unsigned DEFAULT_BORDER = 5;
const unsigned GRID_CHILD_MARGIN_WIDTH = DEFAULT_BORDER * 3;

#endif
